Repository Tezigudo/dotcom-cafe, pull requests merged in 2023-02, with the labels that each got.

#2 "adding dinner menu"
  Menu.md
Labels: size/XS

#1 Add breakfast menu
  Menu.md
Labels: size/XS

#6 Add Beverages Table
  Menu.md
Labels: size/XS

#3 add Snack items
  Menu.md
Labels: size/XS

#5 Add Lunch
  Menu.md
Labels: size/XS

#7 Add sweet menu,price
  Menu.md
Labels: size/XS

#4 add night menu.
  Menu.md
Labels: size/S

#8 Add name
  README.md
Labels: size/S

#9 "adding Readme"
  README.md
Labels: size/S

#10 Add name
  README.md
Labels: size/S

#12 Add Beverage Table in README.md
  README.md
Labels: size/S

#14 Night food
  README.md
Labels: size/M

#13 Snacks
  Menu.md
  README.md
Labels: size/S
